### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by GuilleAngulo** [Morpa/FAQ#1]
Ola @Morpa! massa esse projeto, parabens!

Rodando o projeto localmente percevi que na hora de rodar os testes, estão falhando por causa do **window.fetch** do componente **Search** já que só funciona no browser. Estava pensando que algumas soluções possíveis podem ser:
- Mockar o fetch no Jest com, por exemplo, [jest-fetch-mock](https://www.npmjs.com/package/jest-fetch-mock)
- Usar o pacote [node-fetch](https://www.npmjs.com/package/node-fetch) para que o Jest consiga utilizar o fetch

O que que voce acha? Posso ajudar nessa parte se você quiser 😃

**Comment by Morpa** [comment]
Olá @GuilleAngulo obrigado.
Opa toda ajuda é bem-vinda. Esse projeto é nosso. Eu só iniciei.
Se tiver mais alguma ideia de melhorar alguma coisa não exite.

**Comment by GuilleAngulo** [comment]
Show! Uma coisa relacionada com esse fetch: o que você acha de usar **getStaticProps()**  na index para pegar o FAQ (sustituindo esse fetch)? Assim o projeto aproveitaria a grande vantagen de criar o array de resultados em tempo de build, removeria esse tempo extra para o usuario da chamada no useEffect e acabaria o problema no Jest. Ao final de contas o FAQ é um documento estatico. Se voce topar posso mandar amanha uma PR!

**Comment by Morpa** [comment]
Grande ideia. Não me passou isso pela cabeça. Força nisso.
