### ISSUE TITLE
Flash of Unstyled Text

### ISSUE THREAD

**Issue by GuilleAngulo** [Morpa/FAQ#10]
O site está com problemas de FOUT. Na index, a parte da descripção sofre esse flash quando a página é carregada. Acontece de novo quando um item é selecionado (dessa vez acompanhado de uma nova request para a font). 
(No GIF anexado não é possivel perceber o flash, mas pode testar no site).

![font](https://user-images.githubusercontent.com/50624358/100124314-41c07b80-2e5a-11eb-9459-eacbe5b83409.gif)

Estou preparando uma PR para solucionar, mudando o jeito de importar as fontes.

**Comment by Morpa** [comment]
Estranho né. Isso não deveria acontecer já que as fonts são locais não?

**Comment by GuilleAngulo** [comment]
Eu lembrava de ter visto la no Slack essa [issue](https://willianjusten-cursos.slack.com/archives/C2ENWF90C/p1603320411312000?thread_ts=1603320042.310600&cid=C2ENWF90C). A melhor alternativa parece ser usar o [next-google-fonts](https://github.com/joe-bell/next-google-fonts) no `_app.ts`. Já testei aqui em local e funciona direitinho.
