### ISSUE TITLE
Ajustes na responsividade

### ISSUE THREAD

**Issue by Morpa** [Morpa/FAQ#4]
Ajustar o layout das faqs na versão mobile, pois dependendo do conteúdo o texto está com overflow no box.

**Comment by GuilleAngulo** [comment]
@Morpa Oops, estou com isso agora 😅 Já já mando uma PR para solucionar, desculpa que não testei bem versão mobile.

**Comment by Morpa** [comment]
@GuilleAngulo na verdade eu não tinha feito nada muito aprimorado. Era para não esquecer 😛.
